spring:
  profiles: default
feature:
  x:
    enable: false

---
spring:
  profiles: docker
feature:
  x:
    enable: false
    
---
spring:
  profiles: prod
feature:
  x:
    enable: false
    
---
spring:
  profiles: dev
feature:
  x:
    enable: false
    

